# Generated by Django 5.0.9 on 2026-04-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backuprun',
            new_name='backups_bac_target__a02d54_idx',
            old_name='backups_bac_target__c26f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprun',
            new_name='backups_bac_status_4b63b8_idx',
            old_name='backups_bac_status_43fe41_idx',
        ),
    ]
