# Generated by Django 5.0.9 on 2026-08-10 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backuprun_sharepoint_web_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserdataPruneRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('threshold_mb', models.PositiveIntegerField(default=5)),
                ('targets_scanned', models.PositiveIntegerField(default=0)),
                ('users_pruned_count', models.PositiveIntegerField(default=0)),
                ('total_bytes_freed', models.BigIntegerField(default=0)),
                ('log_output', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='backups_use_started_0143eb_idx'), models.Index(fields=['status', '-started_at'], name='backups_use_status_6756fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserdataPruneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=120)),
                ('user_name', models.CharField(max_length=128)),
                ('actual_name', models.CharField(blank=True, max_length=128)),
                ('original_bytes', models.BigIntegerField(default=0)),
                ('pruned_bytes', models.BigIntegerField(default=0)),
                ('bytes_freed', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backups.userdataprunerun')),
            ],
            options={
                'ordering': ['-bytes_freed'],
            },
        ),
    ]
