# Generated by Django 5.0.9 on 2026-08-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_userdataprunerun_userdatapruneitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseMaintenanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('index_defrag', 'Index Defragmentation & Stats'), ('stale_session', 'Stale Session & Lock Purge'), ('log_pruning', 'Audit Log Retention Pruning'), ('userdata_prune', 'USERDATA Bloat Cleanup')], default='userdata_prune', max_length=32)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('targets_scanned', models.PositiveIntegerField(default=0)),
                ('items_processed_count', models.PositiveIntegerField(default=0)),
                ('metrics_summary', models.TextField(blank=True)),
                ('log_output', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['run_type', '-started_at'], name='backups_dat_run_typ_fd585f_idx'), models.Index(fields=['status', '-started_at'], name='backups_dat_status_1ad570_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatabaseMaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=120)),
                ('item_label', models.CharField(max_length=255)),
                ('metric_before', models.CharField(blank=True, max_length=120)),
                ('metric_after', models.CharField(blank=True, max_length=120)),
                ('detail_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='backups.databasemaintenancerun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
