# Generated by Django 5.0.9 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backups", "0007_schedule_quality_report_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databasemaintenancerun",
            name="run_type",
            field=models.CharField(
                choices=[
                    ("index_defrag", "Index Defragmentation & Stats"),
                    ("stale_session", "Stale Session & Lock Purge"),
                    ("log_pruning", "Audit Log Retention Pruning"),
                    ("userdata_prune", "USERDATA Bloat Cleanup"),
                    ("statistics", "SQL Statistics Refresh"),
                    ("health_check", "Database Physical Integrity Check"),
                    ("p6_background_health", "P6 Native Background Health"),
                ],
                default="userdata_prune",
                max_length=32,
            ),
        ),
    ]
